<template>
  <svg viewBox="0 0 24 24" fill="currentColor" :class="$attrs.class">
    <circle
      cx="9"
      cy="6"
      r="3"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
    />
    <circle
      cx="18"
      cy="6"
      r="2"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
    />
    <circle
      cx="6"
      cy="18"
      r="2"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
    />
    <circle
      cx="18"
      cy="18"
      r="2"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
    />
    <path
      d="M12 9l3 3-3 3M9 12h6"
      stroke="currentColor"
      stroke-width="2"
      fill="none"
    />
    <path d="M8 16l8-8M16 8l-8 8" stroke="currentColor" stroke-width="1" />
  </svg>
</template>
